### ISSUE TITLE
Rule Handling

### ISSUE THREAD

**Issue by phmLabs** [phmLabs/Smoke#15]
It should be possible to overwrite single rules within adding all to the config file.

```yml
additional_rules:
  MyOwnRule: 

rule_overwriting:
 HtmlSize:
  parameters:
    maxSize: 100

```

**Comment by phmLabs** [comment]
```yml
rules:
   settings:
     clear: true
   add:      
      MyOwnRule:
        class: ...
   remove:
      - _HtmlSize
      - _ImageSize
```
