### ISSUE TITLE
don't check images inside javascript templates

### ISSUE THREAD

**Issue by alfredbez** [phmLabs/Smoke#96]
We have something like this in one of our sites:
```html
<script type="text/template" data-template="template-name">
  <img src="<%= icon %>" alt="">
</script>
```
When I run Smoke, it reports something like this:
```
https://domain.de/foo/bar/%3C%25=%20icon%20%25%3E  coming from https://domain.de/foo/bar/baz.html
- Status code 404 found. [rule: _HttpHeaderSuccessStatus]
```

I don't know what's the best way to solve this issue:
* Don't check images inside `<script>` or inside `<script type="text/template">` at all
* Don't check images inside `<script>` tags, if there are special characters like `<` or `{{`

**Comment by phmLabs** [comment]
Didn't test it, but you could use a blacklist filter (use correct escaping):

```yml
blacklist:
   - "<%(.*)"
```

Or just try www.leankoala.com.

**Comment by alfredbez** [comment]
config file
```yml
responseRetriever:
  class: whm\Smoke\Extensions\SmokeResponseRetriever\Retriever\Crawler\Crawler
  parameters:
    startPage: "https://www.testproject.de"
    filters:
      _BlackWhiteListFilter:
        class: whm\Smoke\Extensions\SmokeResponseRetriever\Retriever\Crawler\Filter\BlackWhiteListFilter

      _ValidUrlFilter:
        class: whm\Crawler\Filter\ValidUrlFilter

      _ForeignDomainFilter:
        class: whm\Smoke\Extensions\SmokeResponseRetriever\Retriever\Crawler\Filter\ForeignDomainFilter

whitelist:
 - ^www.testproject.de^

blacklist:
 - "<%(.*)"

rules:
  HtmlSize:
    class: whm\Smoke\Rules\Html\SizeRule
    parameters:
      maxSize: 1

  ImageSize:
      class: whm\Smoke\Rules\Image\SizeRule
      parameters:
        maxSize: 1

reporter:
  XUnitReporter:
    class: whm\Smoke\Extensions\SmokeReporter\Reporter\XUnitReporter
    parameters:
      filename: /tmp/xunit.xml
```

```
~/projects/
→ ~/tmp/learn/php/Smoke.phar custom --config_file="testproject/tmp/smoke.yml"

 Smoke ##development## by Nils Langner


                                                                                                              
  [RuntimeException]                                                                                          
  The extension ("_ResponseRetriever") you are trying to access does not exist. Registered extensions are: .  
                                                                                                              

custom [-c|--config_file CONFIG_FILE] [-b|--bootstrap [BOOTSTRAP]]
```

Is it possible to have only the `blacklist` parameter in my config file? What do I wrong?

**Comment by phmLabs** [comment]
```
options:
  extendDefault: true
```

try to add these lines to your code and remove the responseRetriever part.

**Comment by phmLabs** [comment]
Or add 

```
extensions:
  _ResponseRetriever:
    class: whm\Smoke\Extensions\SmokeResponseRetriever\ResponseRetrieverExtension
```

**Comment by alfredbez** [comment]
Thanks, I use this like so:
```yml
responseRetriever:
  parameters:
    startPage: "https://testproject.de"

options:
  extendDefault: true

blacklist:
 - "#<%(.*)#"
 - "#%3C%25(.*)#"
```
